export const reviewPhotos = [
  "images/group/Rectangle 737.png",
  "images/group/Rectangle 738.png",
  "images/group/Rectangle 739.png",
  "images/group/Rectangle 740.png",
  "images/group/Rectangle 741.png",
  "images/group/Rectangle 742.png",
  "images/group/Rectangle 743.png",
  "images/group/Rectangle 744.png",
  "images/group/Rectangle 745.png",
  "images/group/Rectangle 746.png",
  "images/group/Rectangle 747.png",
  "images/group/Rectangle 748.png",
  "images/group/Rectangle 749.png",
  "images/group/Rectangle 750.png",
  "images/group/Rectangle 751.png",
  "images/group/Rectangle 752.png",
  "images/group/Rectangle 753.png",
  "images/group/Rectangle 754.png",
  "images/group/Rectangle 755.png",
  "images/group/Rectangle 756.png",
  "images/group/Rectangle 757.png",
  "images/group/Rectangle 758.png",
];
